apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ax8zg2hnb-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1c5ec0f724.1r9a.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:8afe7935011c15c950c9e0c9c2a1c5e28db385ec@sha256:88adca6b1ca71c7e64f0ab382d393cd83dcc320fb0e89b2fedfac82d496a1960
          name: container-image
